[package]
name = "infrastructure-owl"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
worker = { workspace = true }
serde_json = { workspace = true }
domain-owl = { path = "../domain-owl" }
